import { existsSync, readFileSync, rmSync } from "node:fs";
import { dirname } from "node:path";
import { writeFileAtomic } from "../core/fsx.js";
import { home } from "../core/paths.js";

const MARKER = "# looprch shim";

export function shimContent(): string {
  return `#!/bin/sh\n${MARKER}: generated by looprch install; do not edit\nexec node "\${LOOPRCH_HOME:-$HOME/.looprch}/current/dist/looprch.mjs" "$@"\n`;
}

export interface ShimResult {
  path: string;
  written: boolean;
  foreign: boolean;
  on_path: boolean;
  path_hint: string | null;
}

export function isOurShim(path: string): boolean {
  return existsSync(path) && readFileSync(path, "utf8").includes(MARKER);
}

export function writeShim(): ShimResult {
  const path = home.shim();
  const foreign = existsSync(path) && !isOurShim(path);
  if (!foreign) writeFileAtomic(path, shimContent(), 0o755);
  const dir = dirname(path);
  const onPath = (process.env.PATH ?? "").split(":").includes(dir);
  return {
    path,
    written: !foreign,
    foreign,
    on_path: onPath,
    path_hint: onPath ? null : `export PATH="$HOME/.local/bin:$PATH"   # add this line to ~/.bashrc or ~/.zshrc`,
  };
}

export function removeShim(): boolean {
  const path = home.shim();
  if (!isOurShim(path)) return false;
  rmSync(path, { force: true });
  return true;
}
