import { join } from "node:path";
import { writeFileAtomic } from "./fsx.js";
import { projectPaths } from "./paths.js";
import { plannedTests, type Contract } from "./contract.js";
import type { Current } from "./state.js";
import type { PhaseDef } from "../sev3/manifest.js";

const cell = (s: string): string => s.replace(/\|/g, "\\|").replace(/\n/g, " ");

/**
 * The traceability matrix of a phase, generated from state only (no model writes it):
 * requirement → obligation or deferral → decisions → work packages → planned tests → the
 * Tester's verification and its testcases → the Reviewer's contract status.
 */
export function traceabilityMarkdown(phase: PhaseDef, contract: Contract | null, c: Pick<Current, "tester_verifications" | "contract_review">): string {
  const lines = [`# Traceability: ${phase.id}`, "", "Generated by Looprch from the contract, the Tester's verifications (bound to the gate evidence) and the reviews. Do not edit.", ""];
  if (!contract) return `${lines.join("\n")}\n(no contract.json)\n`;
  const verifs = new Map((c.tester_verifications ?? []).map((v) => [v.id, v]));
  const review = new Map((c.contract_review ?? []).map((x) => [x.id, x.status]));
  const tests = plannedTests(contract);
  const wps = contract.work_packages ?? [];
  const verif = (id: string): string => {
    const v = verifs.get(id);
    return v ? `${v.status}${v.tests.length ? `: ${v.tests.slice(0, 3).join(", ")}${v.tests.length > 3 ? ` +${v.tests.length - 3}` : ""}` : ""}` : "not verified";
  };
  lines.push("| Requirement | Contract | Kind | Decisions | Packages | Planned tests | Tester | Review |", "|---|---|---|---|---|---|---|---|");
  const reqs = phase.requirements.length ? phase.requirements : [...new Set([...contract.obligations, ...contract.deferrals].flatMap((x) => x.requirements))];
  for (const req of reqs) {
    const items = [...contract.obligations.filter((o) => o.requirements.includes(req)), ...contract.deferrals.filter((d) => d.requirements.includes(req))];
    if (!items.length) {
      lines.push(`| ${req} | **uncovered** | | | | | | |`);
      continue;
    }
    for (const x of items) {
      const isObligation = "statement" in x;
      const decisions = (contract.decisions ?? []).filter((d) => d.obligations.includes(x.id) || d.requirements.includes(req)).map((d) => d.id);
      const packages = wps.filter((w) => w.obligations?.includes(x.id)).map((w) => w.id);
      const planned = tests.filter((t) => t.obligation === x.id).map((t) => `${t.id} (${t.kind}): ${verif(t.id)}`);
      lines.push(
        `| ${req} | ${x.id}${isObligation ? "" : ` → ${x.to_phase}`} | ${isObligation ? x.kind : "deferral"} | ${decisions.join(", ") || "-"} | ${packages.join(", ") || "-"} | ${cell(planned.join("; ") || "-")} | ${cell(verif(x.id))} | ${review.get(x.id) ?? "not reviewed"} |`,
      );
    }
  }
  const unmapped = tests.filter((t) => !contract.obligations.some((o) => o.id === t.obligation));
  if (unmapped.length) lines.push("", `Planned tests without an obligation: ${unmapped.map((t) => t.id).join(", ")}`);
  return `${lines.join("\n")}\n`;
}

export function writeTraceability(root: string, phaseId: string, phase: PhaseDef, contract: Contract | null, c: Pick<Current, "tester_verifications" | "contract_review">): string {
  const path = join(projectPaths(root).phase(phaseId), "traceability.md");
  writeFileAtomic(path, traceabilityMarkdown(phase, contract, c));
  return path;
}
