import type { AgentId } from "../core/config.js";
import type { Role } from "../core/constants.js";

export const GENERATED_MARKER = "generated by looprch: do not edit";

export interface GeneratedFile {
  /** Path relative to the project root. */
  path: string;
  content: string;
}

export type Verification = "verified" | "unverified" | "false" | "not_run";

export interface DirectSupport {
  subagentFile(role: Role, model: string, readOnly: boolean): GeneratedFile;
  resumable: boolean;
  /** How the Lead spawns the native subagent; shown in skills and run_role actions. */
  spawnHint: string;
}

export interface DelegateSupport {
  skill: string;
  sessionField: "threadId" | "sessionId" | "conversationId";
  resumeFlag: "--session" | "--conversation";
  resumable: boolean;
  readOnly: "enforced" | "best-effort" | "none";
  effortFlag: "--effort" | "--variant" | null;
  cleanEnv: boolean;
  modelFormat?: "provider/model";
  /** Flags passed only to write runs (never with --read-only). */
  writeFlags?: string[];
  /** The CLI's own print-mode timeout; set to the run timeout so it does not stop earlier than the watchdog. */
  printTimeoutFlag?: "--print-timeout";
  /** A reported model list proves the CLI is logged in (discovery has no auth probe for it). */
  authFromModels?: boolean;
}

export interface AgentAdapter {
  id: AgentId;
  displayName: string;
  /** First binary found on PATH wins. */
  binaries: string[];
  /** Project directories where lr-* skills must appear. */
  skillDirs: string[];
  followsSymlinks: boolean | "unverified";
  invoke(skill: string): string;
  extraFiles?(skills: readonly string[]): GeneratedFile[];
  direct?: DirectSupport;
  delegate?: DelegateSupport;
  quotalensProvider?: string;
  /** Environment variables that indicate the Lead runs inside this host (hints only). */
  envMarkers: string[];
  postInstallNotes: string[];
  /** Gitignore patterns for files this adapter generates. */
  generatedGlobs: string[];
  verified: Record<"skills" | "invoke" | "direct" | "resume" | "readOnly", Verification>;
  experimental?: boolean;
}

export const RESULT_LINE = "Follow the brief you are given exactly; return the result block it asks for.";

export function roleTitle(role: Role): string {
  return role.replace("_", " ");
}
