import { test, describe } from "node:test";
import assert from "node:assert/strict";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { tmp } from "../helpers/tmp.js";
import { ADAPTERS, allAdapters, agentCaps, detectHosts } from "../../src/agents/index.js";
import { GENERATED_MARKER } from "../../src/agents/types.js";
import { decideLinkModes } from "../../src/install/links.js";
import { AGENTS_BEGIN, AGENTS_END, upsertBlock, desiredAgentFiles, gitignoreBlock } from "../../src/install/project-files.js";
import { defaultConfig } from "../../src/core/config.js";

describe("agents", () => {
  test("invoke syntax per adapter", () => {
    assert.equal(ADAPTERS.codex.invoke("lr-init"), "$lr-init");
    assert.equal(ADAPTERS.cursor.invoke("lr-init"), "/lr-init");
    assert.equal(ADAPTERS.kimi.invoke("lr-init"), "/skill:lr-init");
    assert.equal(ADAPTERS.opencode.invoke("lr-init"), "/lr-init");
    assert.equal(ADAPTERS.agy.invoke("lr-init"), "/lr-init");
    assert.equal(ADAPTERS.hermes.invoke("lr-init"), "/lr-init");
    assert.equal(ADAPTERS.grok.invoke("lr-init"), "/lr-init");
  });

  test("capabilities: hermes has no relay, kimi no read-only, opencode needs provider/model", () => {
    const caps = agentCaps();
    assert.equal(caps.hermes.delegate, false);
    assert.equal(caps.hermes.direct, false);
    assert.equal(caps.kimi.readOnly, "none");
    assert.equal(caps.opencode.modelFormat, "provider/model");
    assert.equal(caps.cursor.direct, true);
    assert.equal(caps.agy.direct, false);
  });

  test("generated subagent files carry the ownership marker and model (snapshot)", () => {
    for (const a of allAdapters()) {
      if (!a.direct) continue;
      const f = a.direct.subagentFile("reviewer", "model-x", true);
      assert.ok(f.content.includes(GENERATED_MARKER), a.id);
      assert.ok(f.content.includes("model-x"), a.id);
      assert.match(f.path, /lr-reviewer/);
    }
    assert.equal(
      ADAPTERS.cursor.direct!.subagentFile("planner", "m1", false).content,
      "---\nname: lr-planner\ndescription: Looprch planner role. Use only when Looprch hands you a brief.\nmodel: m1\n---\n<!-- generated by looprch: do not edit -->\nFollow the brief you are given exactly; return the result block it asks for.\n",
    );
    assert.match(ADAPTERS.codex.direct!.subagentFile("reviewer", "m2", true).content, /sandbox_mode = "read-only"/);
    assert.match(ADAPTERS.opencode.direct!.subagentFile("reviewer", "p/m", true).content, /edit: deny/);
  });

  test("desired files follow configured Direct roles only", () => {
    const cfg = defaultConfig();
    cfg.agents = ["cursor", "codex"];
    cfg.roles.planner = { mode: "direct", agent: "cursor", model: "m", fallbacks: [] };
    cfg.roles.tester = { mode: "delegate", agent: "codex", model: "m", fallbacks: [] };
    assert.deepEqual(desiredAgentFiles(cfg).map((f) => f.path), [".cursor/agents/lr-planner.md"]);
  });

  test("host detection from env markers", () => {
    assert.deepEqual(detectHosts({ CURSOR_AGENT: "1" }), ["cursor"]);
    assert.deepEqual(detectHosts({ CODEX_THREAD_ID: "x", OPENCODE: "1" }), ["codex", "opencode"]);
    assert.deepEqual(detectHosts({}), []);
  });

  test("link mode decision", () => {
    assert.deepEqual(decideLinkModes(["codex", "opencode"], false), { ".agents/skills": "symlink" });
    assert.deepEqual(decideLinkModes(["codex", "cursor"], false), { ".agents/skills": "copy" });
    assert.deepEqual(decideLinkModes(["codex"], true), { ".agents/skills": "copy" });
    assert.deepEqual(decideLinkModes(["grok"], false), { ".grok/skills": "copy" });
  });

  test("gitignore block lists generated globs unless committed", () => {
    const cfg = defaultConfig();
    cfg.agents = ["cursor"];
    assert.match(gitignoreBlock(cfg, [".agents/skills"]), /\.cursor\/agents\/lr-\*\.md/);
    cfg.integrations.commit_generated = true;
    assert.doesNotMatch(gitignoreBlock(cfg, [".agents/skills"]), /\.cursor\/agents/);
  });
});

describe("AGENTS.md block", () => {
  test("insert, update, no duplicate", () => {
    const d = tmp();
    const p = join(d, "AGENTS.md");
    assert.equal(upsertBlock(p, AGENTS_BEGIN, AGENTS_END, "v1"), "created");
    assert.equal(upsertBlock(p, AGENTS_BEGIN, AGENTS_END, "v1"), "unchanged");
    assert.equal(upsertBlock(p, AGENTS_BEGIN, AGENTS_END, "v2"), "updated");
    assert.equal(readFileSync(p, "utf8"), `${AGENTS_BEGIN}\nv2\n${AGENTS_END}\n`);
  });

  test("preserves surrounding user text", () => {
    const d = tmp();
    mkdirSync(d, { recursive: true });
    const p = join(d, "AGENTS.md");
    writeFileSync(p, `top\n\n${AGENTS_BEGIN}\nold\n${AGENTS_END}\n\nbottom\n`);
    upsertBlock(p, AGENTS_BEGIN, AGENTS_END, "new");
    assert.equal(readFileSync(p, "utf8"), `top\n\n${AGENTS_BEGIN}\nnew\n${AGENTS_END}\n\nbottom\n`);
  });
});
